# Generated by Django 4.2.4 on 2024-11-05 05:36

from django.db import migrations, models
import django_tidb.fields.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", django_tidb.fields.vector.VectorField(dimensions=3)),
            ],
            options={
                "indexes": [
                    django_tidb.fields.vector.VectorIndex(
                        django_tidb.fields.vector.L2Distance("embedding"), name="idx_l2"
                    ),
                    django_tidb.fields.vector.VectorIndex(
                        django_tidb.fields.vector.CosineDistance("embedding"),
                        name="idx_cos",
                    ),
                ],
            },
        ),
    ]
