# Generated by Django 4.2.4 on 2024-06-25 01:51

from django.db import migrations, models
import django_tidb.fields.vector


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", django_tidb.fields.vector.VectorField(dimensions=3)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentWithIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "embedding",
                    django_tidb.fields.vector.VectorField(
                        db_comment="hnsw(distance=cosine)", dimensions=3
                    ),
                ),
            ],
        ),
    ]
